### ISSUE TITLE
Question about user/server mappings

### ISSUE THREAD

**Issue by k4kfh** [srieger1/gns3-proxy#2]
This is not really an issue with the program, I just need clarification on something.

Are you required to have one GNS3 server per user in order to maintain user isolation? i.e. is the user isolation handled by mapping users to servers 1:1?

Or assuming the host had enough compute power, could I run a single instance of GNS3 server and use gns3-proxy to "bolt on" user isolation? For instance, if I configure gns3-proxy and map both `bob` and `sally` to the same GNS3 server instance, will `bob` be able to see `sally`'s projects or not?

**Comment by srieger1** [comment]
As GNS3 does not really offer different users having different permissions, you're correct, if you want to be sure, that users are really isolated from each other, safest option would be to configure gns3-proxy to send them to different gns3 server backends. However, the gns3-proxy also offers another option that spares you from running multiple GNS3 servers. You can use the project-filter option in the gns3-proxy config and limit the projects that, e.g., bob and sally, are allowed to use/open etc. based on project name. An example is included in [gns3_proxy_config.ini](https://github.com/srieger1/gns3-proxy/blob/develop/gns3_proxy_config.ini). We combine this option together with rules in the `[deny]` section, to also do not allow users to modify projects etc.
