### ISSUE TITLE
Pass config file into Docker container?

### ISSUE THREAD

**Issue by k4kfh** [srieger1/gns3-proxy#3]
Is there a preferred way of passing a config file into the docker container? I am looking for a way to easily create a container with a given config file, and I'm wondering if there's a way to do it without logging into the container and manually editing the file.

**Comment by srieger1** [comment]
Yes! You can take a look at the provided startup file example: https://github.com/srieger1/gns3-proxy/blob/develop/scripts/docker-container-example/start-gns3proxy-container. It mounts a proxy config and crontab file from the current directory to be available in the container. This is also how we use it in the local setup for our lab.
