### ISSUE TITLE
gns3_proxy_replicate_projects not including snapshots

### ISSUE THREAD

**Issue by Ph0b055** [srieger1/gns3-proxy#5]
Is there an easy way to have the project replication include the snapshots from the source server's projects?

**Comment by srieger1** [comment]
Easiest way would be the copy/migrate function that is directly offered in the menu of GNS3 server. However, this is a full scp/rsync based copy of /opt/gns3/projects and /opt/gns3/images. Snapshots are saved in a subdirectory snapshots in the project. Maybe I can find a way to check if a project that should be replicated contains snapshots and then also copy them. Strange however, that they are not already included, as I use the regulare GNS3 API to download the project.

**Comment by Ph0b055** [comment]
yeah, the replicate_projects script seems to ignore the snapshot folder altogether. After a quick look at the GNS3/gns3-server/tree/master/docs/api/examples repo they seem to have split out the project and snapshot API calls( just a guess, I don't know much about this).

I know when you try to export a project in the GNS3 application "include snapshots" is an additional checkbox so the API may behave the same way and not assume you want them by default.

**Comment by srieger1** [comment]
You're right! The option to also export the snapshots seams to be new! I'm pretty sure I can integrate that in the replicate_projects script, though I'd also be happy to receive a PR for that ;) 

We currently do not use snapshots ourselves, as they tend to break things (running containers etc.) some years ago, when we tried that option. Hence we now use replicate_projects script etc. to ensure a fresh copy of the project and its dependencies. However, it seams as snapshots are a reliable and better option now, depending on the use case.

**Comment by Ph0b055** [comment]
I'm glad you are interested in getting snapshots incorporated into the cron jobs! I'll send you an email to describe my use case and maybe it will make its way into the repo in the event someone else has the same need.

**Comment by srieger1** [comment]
As it turned out, it was easier than I thought. There are URL params that can be used to include snaphosts, base images and reset mac addresses now in the API of GNS3. 

I added an option "--include-snapshots" to the new version of gns3_proxy_replicate_projects.py and gns3_proxy_manage_projects.py. When you use this option, snapshots are also exported and replicated. That should add the functionality that you asked for.
